apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lsapi-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lsapi
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50    # scale if cpu reach to "targetCPUUtilizationPercentage" of request cpu in config file (e.g. 50% of 500m)